# GÃ©nration Data Cours NF26

**Auteur :** Cyprien Gilet

In [1]:
#pip install pyspark

In [2]:
import os
os.environ["PYARROW_IGNORE_TIMEZONE"] = "1"

In [3]:
import pandas as pd
import numpy as np
from datetime import datetime, date

import pyspark.pandas as ps
from pyspark.sql import SparkSession
from pyspark.sql import Row

In [5]:
spark = SparkSession.builder.getOrCreate()

## Object Creation

In [6]:
from datetime import timedelta
from dateutil import parser

def generation_data_patients(n): 

    # Table Administration
    key_consultation = [] #OK
    key_patient = [] #OK
    name_patients = [] #OK
    firstname_patients = [] #OK
    Num_Secu = [] # OK
    dates_In = [] #OK
    pathology = [] #OK
    dates_Out = [] #OK
    
    # Table Medecin
    nbMedecin = 30 #OK
    key_medecin = [] #OK
    name_medecin = [] #OK
    firstname_medecin = [] #OK
    speciality = ['Generaliste','Chirurgien','Dermatologiste','Dentiste','Cardiologue'] #OK
    specialyty_Medecin = [] #OK
    for l in range(nbMedecin): 
        key_medecin.append('keyMedecin' + str(l)) #OK
        name_medecin.append('NameMedecin' + str(l)) #OK
        firstname_medecin.append('FirstNameMedecin' + str(l)) #OK
        idxSpecility = np.random.poisson(lam=1, size=1)[0] #OK
        if idxSpecility > 4:
            idxSpecility = 4 #OK
        specialyty_Medecin.append(speciality[idxSpecility]) #OK
    MedecinConsult = [] #OK
    
    # Patient Profile
    age = [] #OK
    weight = [] #OK
    temperature = [] #OK
    tension = [] #OK
    diabete = [] #OK
    
    # Table Treatment
    key_treatment_Patient = [] #OK
    key_treatment = [] #OK
    treatment = [] #OK
    key_medicament = [] #OK
    name_medicament = [] #OK
    quantity_medicament = [] #OK
    for t in range(1000):
        key_medicament.append('KeyMed' + str(t))
        name_medicament.append('Medicament' + str(t))
    
    # Table Chambre
    key_chambre = [] #OK
    chambre_number = [] #OK
    numberChambre = 104
    for c in range(numberChambre):
        key_chambre.append('KeyChambre' + str(c+1))
        chambre_number.append('C' + str(f'{c+1:03}'))
    chambre_Number_Patient = [] #OK
    key_chambre_Patient = [] #OK
    
    
    
    year = 2023
    str_year = str(year)
    all_dates_in = np.sort(np.random.randint(1, 365, n))
    
    for i in range(n):
        
        # key Consultation :
        key_consultation.append('KeyConsult' + str(i))
        
        # key Patient :
        idx_patient = str(np.random.randint(1, 50000, 1)[0])
        key_patient.append('KeyPatient' + idx_patient)
        
        # Num Secu :
        SecuOK = np.random.binomial(1, 0.99, 1)[0]
        if SecuOK == 1:
            Num_Secu.append('NS' + str(f'{i+1:05}'))
        if SecuOK == 0:
            Num_Secu.append('NULL')
    
        # Name :
        name_patients.append('Name' + idx_patient)

        # First Name :
        firstname_patients.append('FistName' + idx_patient)
    
        # Pathology :
        idx_pathology = np.random.randint(1, 100, 1)[0]
        pathology.append('Pathology' + str(idx_pathology))
        
        # Medecin :
        MedecinConsult.append(key_medecin[np.random.randint(1, nbMedecin, 1)[0]])
        
        # initializing year and day number
        day_num_In = all_dates_in[i]
        
        if idx_pathology <= 60 :
            lmbda = 1.0
            # Age :
            age.append(np.random.poisson(lam=20, size=1)[0])
            # Weight :
            weight.append(np.random.normal(60, 3, 1)[0])
            # Temperature :
            temperature.append(np.random.normal(37.5, 0.1, 1)[0])
            # Tension :
            tension.append(np.random.normal(116, 20, 1)[0])
            # Diabete :
            diabete.append(np.random.binomial(1, 0.1, 1)[0])
            # Treatment :
            nbMed = np.random.randint(1, 4, 1)[0]
            idxMed = np.random.randint(1, 1000, nbMed)
            for m in range(nbMed):
                key_treatment.append('KeyTreatment' + str(i))
                treatment.append(key_medicament[idxMed[m]])
                quantity_medicament.append(np.random.randint(1, 4, 1)[0])
        if idx_pathology > 60 and idx_pathology <= 70 :
            lmbda = 3.0
            # Age :
            age.append(np.random.poisson(lam=40, size=1)[0])
            # Weight :
            weight.append(np.random.normal(75, 7, 1)[0])
            # Temperature :
            temperature.append(np.random.normal(38.5, 0.1, 1)[0])
            # Tension :
            tension.append(np.random.normal(110, 5, 1)[0])
            # Diabete :
            diabete.append(np.random.binomial(1, 0.1, 1)[0])
            # Treatment :
            nbMed = np.random.randint(1, 4, 1)[0]
            idxMed = np.random.randint(1, 5, nbMed)
            for m in range(nbMed):
                key_treatment.append('KeyTreatment' + str(i))
                treatment.append(key_medicament[idxMed[m]])
                quantity_medicament.append(np.random.randint(1, 4, 1)[0])
        if idx_pathology > 70 and idx_pathology <= 80 :
            lmbda = 6.0
            # Age :
            age.append(np.random.poisson(lam=70, size=1)[0])
            # Weight :
            weight.append(np.random.normal(70, 4, 1)[0])
            # Temperature :
            temperature.append(np.random.normal(40, 0.1, 1)[0])
            # Tension :
            tension.append(np.random.normal(120, 5, 1)[0])
            # Diabete :
            diabete.append(np.random.binomial(1, 0.2, 1)[0])
            # Treatment :
            nbMed = np.random.randint(1, 4, 1)[0]
            idxMed = np.random.randint(1, 5, nbMed)
            for m in range(nbMed):
                key_treatment.append('KeyTreatment' + str(i))
                treatment.append(key_medicament[idxMed[m]])
                quantity_medicament.append(np.random.randint(1, 4, 1)[0])
        if idx_pathology > 80 and idx_pathology <= 90 :
            lmbda = 10.0
            # Age :
            age.append(np.random.poisson(lam=50, size=1)[0])
            # Weight :
            weight.append(np.random.normal(80, 3, 1)[0])
            # Temperature :
            temperature.append(np.random.normal(38, 0.1, 1)[0])
            # Tension :
            tension.append(np.random.normal(90, 2, 1)[0])
            # Diabete :
            diabete.append(np.random.binomial(1, 0.7, 1)[0])
            # Treatment :
            nbMed = np.random.randint(1, 4, 1)[0]
            idxMed = np.random.randint(1, 90, nbMed)
            for m in range(nbMed):
                key_treatment.append('KeyTreatment' + str(i))
                treatment.append(key_medicament[idxMed[m]])
                quantity_medicament.append(np.random.randint(1, 4, 1)[0])
        if idx_pathology > 90 and idx_pathology <= 100 :
            lmbda = 18.0
            # Age :
            age.append(np.random.poisson(lam=40, size=1)[0])
            # Weight :
            weight.append(np.random.normal(75, 4, 1)[0])
            # Temperature :
            temperature.append(np.random.normal(40.5, 0.1, 1)[0])
            # Tension :
            tension.append(np.random.normal(80, 2, 1)[0])
            # Diabete :
            diabete.append(np.random.binomial(1, 0.2, 1)[0])
            # Treatment :
            nbMed = np.random.randint(1, 4, 1)[0]
            idxMed = np.random.randint(1, 1000, nbMed)
            for m in range(nbMed):
                key_treatment.append('KeyTreatment' + str(i))
                treatment.append(key_medicament[idxMed[m]])
                quantity_medicament.append(np.random.randint(1, 4, 1)[0])
                
        key_treatment_Patient.append('KeyTreatment' + str(i))
            
        number_days_stay = np.random.poisson(lam=lmbda, size=1)[0]
        day_num_Out = day_num_In + number_days_stay
            

        # creating date string
        date_str = str_year + "-01-01"  # January 1st of the given year
        date_obj = parser.parse(date_str)  # parse date string to datetime object

        # adding days to datetime object for date_In
        date_res_In = date_obj + timedelta(days=int(day_num_In) - 1)
        dates_In.append(date_res_In)
        
        # adding days to datetime object for date_Out
        date_res_out = date_obj + timedelta(days=int(day_num_Out) - 1)
        dates_Out.append(date_res_out)


        # Chambre ?
        if number_days_stay > 0:
            idxChambre = np.random.randint(numberChambre, size=1)[0]
            key_chambre_Patient.append(key_chambre[idxChambre])
            chambre_Number_Patient.append(chambre_number[idxChambre])
        if number_days_stay == 0:
            key_chambre_Patient.append('NULL')
            chambre_Number_Patient.append('NULL')
        
        
        
        
    # Table Administration
    pandas_administration_df = pd.DataFrame(
        {'KeyConsult': key_consultation,
         'KeyPatient': key_patient,
         'Name': name_patients,
         'FirstName': firstname_patients,
         'NumSecu': Num_Secu,
         'Date_In': dates_In,
         'Pathology': pathology,
         'KeyChambre': key_chambre_Patient,
         'ChambreNumber': chambre_Number_Patient,
         'Date_Out': dates_Out
        }
    )


    # Table Medecin
    pandas_medecin_df = pd.DataFrame(
        {'KeyMedecin': key_medecin,
         'NameMedecin': name_medecin,
         'FirstNameMedecin': firstname_medecin,
         'SpecialityMedecin': specialyty_Medecin
        }
    )


    # Table Diagnostic
    pandas_diagnostic_df = pd.DataFrame(
        {'KeyConsult': key_consultation,
         'KeyMedecin': MedecinConsult,
         'KeyPatient': key_patient,
         'NamePatient': name_patients,
         'FirstNamePatient': firstname_patients,
         'NumSecu': Num_Secu,
         'Age': age,
         'Weight': weight,
         'Temperature': temperature,
         'Tension': tension,
         'Diabete': diabete,
         'Pathology': pathology,
         'KeyTreatment': key_treatment_Patient
        }
    )


    # Table Treatment
    pandas_treatment_df = pd.DataFrame(
        {'KeyTreatment': key_treatment,
         'KeyMedicament': treatment,
         'QuantityMedicament': quantity_medicament
        }
    )
    
    
    # Table Medicaments
    pandas_medicament_df = pd.DataFrame(
        {'KeyMedicament': key_medicament,
         'NameMedicament': name_medicament
        }
    )


    # Table Chambre
    pandas_chambre_df = pd.DataFrame(
        {'KeyChambre': key_chambre,
         'ChambreNumber': chambre_number
        }
    )

        
        
        
    return pandas_administration_df, pandas_medecin_df, pandas_diagnostic_df, pandas_treatment_df, pandas_medicament_df, pandas_chambre_df

In [7]:
pandas_administration_df, pandas_medecin_df, pandas_diagnostic_df, pandas_treatment_df, pandas_medicament_df, pandas_chambre_df = generation_data_patients(50000)

In [8]:
pandas_administration_df.head(20)

,KeyConsult,KeyPatient,Name,FirstName,NumSecu,Date_In,Pathology,KeyChambre,ChambreNumber,Date_Out
0,KeyConsult0,KeyPatient9284,Name9284,FistName9284,NS00001,2023-01-01,Pathology3,NULL,NULL,2023-01-01
1,KeyConsult1,KeyPatient14406,Name14406,FistName14406,NS00002,2023-01-01,Pathology32,NULL,NULL,2023-01-01
2,KeyConsult2,KeyPatient548,Name548,FistName548,NS00003,2023-01-01,Pathology15,KeyChambre31,C031,2023-01-02
3,KeyConsult3,KeyPatient24095,Name24095,FistName24095,NS00004,2023-01-01,Pathology58,KeyChambre28,C028,2023-01-03
4,KeyConsult4,KeyPatient21604,Name21604,FistName21604,NS00005,2023-01-01,Pathology55,KeyChambre84,C084,2023-01-03
5,KeyConsult5,KeyPatient13149,Name13149,FistName13149,NS00006,2023-01-01,Pathology13,KeyChambre20,C020,2023-01-03
6,KeyConsult6,KeyPatient25415,Name25415,FistName25415,NS00007,2023-01-01,Pathology83,KeyChambre59,C059,2023-01-13
7,KeyConsult7,KeyPatient5220,Name5220,FistName5220,NS00008,2023-01-01,Pathology85,KeyChambre65,C065,2023-01-11
8,KeyConsult8,KeyPatient13496,Name13496,FistName13496,NS00009,2023-01-01,Pathology74,KeyChambre75,C075,2023-01-07
9,KeyConsult9,KeyPatient17445,Name17445,FistName17445,NS00010,2023-01-01,Pathology18,KeyChambre67,C067,2023-01-03
10,KeyConsult10,KeyPatient13630,Name13630,FistName13630,NS00011,2023-01-01,Pathology84,KeyChambre44,C044,2023-01-09
11,KeyConsult11,KeyPatient23327,Name23327,FistName23327,NS00012,2023-01-01,Pathology8,NULL,NULL,2023-01-01
12,KeyConsult12,KeyPatient41238,Name41238,FistName41238,NS00013,2023-01-01,Pathology94,KeyChambre85,C085,2023-01-22
13,KeyConsult13,KeyPatient31549,Name31549,FistName31549,NS00014,2023-01-01,Pathology79,KeyChambre102,C102,2023-01-08
14,KeyConsult14,KeyPatient28987,Name28987,FistName28987,NS00015,2023-01-01,Pathology70,KeyChambre41,C041,2023-01-05
15,KeyConsult15,KeyPatient21991,Name21991,FistName21991,NS00016,2023-01-01,Pathology58,KeyChambre25,C025,2023-01-02
16,KeyConsult16,KeyPatient28078,Name28078,FistName28078,NS00017,2023-01-01,Pathology30,KeyChambre36,C036,2023-01-02
17,KeyConsult17,KeyPatient8406,Name8406,FistName8406,NS00018,2023-01-01,Pathology76,KeyChambre1,C001,2023-01-07
18,KeyConsult18,KeyPatient17925,Name17925,FistName17925,NS00019,2023-01-01,Pathology91,KeyChambre25,C025,2023-01-19
19,KeyConsult19,KeyPatient23661,Name23661,FistName23661,NS00020,2023-01-01,Pathology40,KeyChambre90,C090,2023-01-03

In [9]:
pandas_medecin_df.head(10)

    KeyMedecin   NameMedecin   FirstNameMedecin SpecialityMedecin
0  keyMedecin0  NameMedecin0  FirstNameMedecin0        Chirurgien
1  keyMedecin1  NameMedecin1  FirstNameMedecin1       Generaliste
2  keyMedecin2  NameMedecin2  FirstNameMedecin2        Chirurgien
3  keyMedecin3  NameMedecin3  FirstNameMedecin3        Chirurgien
4  keyMedecin4  NameMedecin4  FirstNameMedecin4       Generaliste
5  keyMedecin5  NameMedecin5  FirstNameMedecin5       Generaliste
6  keyMedecin6  NameMedecin6  FirstNameMedecin6    Dermatologiste
7  keyMedecin7  NameMedecin7  FirstNameMedecin7        Chirurgien
8  keyMedecin8  NameMedecin8  FirstNameMedecin8       Generaliste
9  keyMedecin9  NameMedecin9  FirstNameMedecin9       Generaliste

In [10]:
pandas_diagnostic_df.head(10)

,KeyConsult,KeyMedecin,KeyPatient,NamePatient,FirstNamePatient,NumSecu,Age,Weight,Temperature,Tension,Diabete,Pathology,KeyTreatment
0,KeyConsult0,keyMedecin16,KeyPatient9284,Name9284,FistName9284,NS00001,27,66.733217,37.503402,112.083331,0,Pathology3,KeyTreatment0
1,KeyConsult1,keyMedecin28,KeyPatient14406,Name14406,FistName14406,NS00002,17,57.787653,37.533841,116.016471,0,Pathology32,KeyTreatment1
2,KeyConsult2,keyMedecin25,KeyPatient548,Name548,FistName548,NS00003,18,59.214056,37.537445,124.930596,0,Pathology15,KeyTreatment2
3,KeyConsult3,keyMedecin13,KeyPatient24095,Name24095,FistName24095,NS00004,22,59.152184,37.591028,84.728456,0,Pathology58,KeyTreatment3
4,KeyConsult4,keyMedecin6,KeyPatient21604,Name21604,FistName21604,NS00005,10,60.958931,37.517863,95.402268,0,Pathology55,KeyTreatment4
5,KeyConsult5,keyMedecin6,KeyPatient13149,Name13149,FistName13149,NS00006,18,59.546759,37.638112,82.211680,0,Pathology13,KeyTreatment5
6,KeyConsult6,keyMedecin20,KeyPatient25415,Name25415,FistName25415,NS00007,54,76.527208,37.906521,94.510178,1,Pathology83,KeyTreatment6
7,KeyConsult7,keyMedecin4,KeyPatient5220,Name5220,FistName5220,NS00008,58,78.575818,38.118216,89.664356,0,Pathology85,KeyTreatment7
8,KeyConsult8,keyMedecin5,KeyPatient13496,Name13496,FistName13496,NS00009,76,75.333390,40.086787,126.426719,0,Pathology74,KeyTreatment8
9,KeyConsult9,keyMedecin2,KeyPatient17445,Name17445,FistName17445,NS00010,22,61.094638,37.587899,120.979594,0,Pathology18,KeyTreatment9

In [11]:
pandas_treatment_df.head(10)

    KeyTreatment KeyMedicament  QuantityMedicament
0  KeyTreatment0     KeyMed166                   1
1  KeyTreatment0     KeyMed154                   2
2  KeyTreatment1     KeyMed110                   1
3  KeyTreatment1     KeyMed823                   1
4  KeyTreatment2     KeyMed523                   1
5  KeyTreatment3      KeyMed86                   3
6  KeyTreatment3     KeyMed737                   2
7  KeyTreatment4     KeyMed688                   2
8  KeyTreatment4     KeyMed340                   1
9  KeyTreatment5     KeyMed604                   1

In [12]:
pandas_medicament_df.head(20)

   KeyMedicament NameMedicament
0        KeyMed0    Medicament0
1        KeyMed1    Medicament1
2        KeyMed2    Medicament2
3        KeyMed3    Medicament3
4        KeyMed4    Medicament4
5        KeyMed5    Medicament5
6        KeyMed6    Medicament6
7        KeyMed7    Medicament7
8        KeyMed8    Medicament8
9        KeyMed9    Medicament9
10      KeyMed10   Medicament10
11      KeyMed11   Medicament11
12      KeyMed12   Medicament12
13      KeyMed13   Medicament13
14      KeyMed14   Medicament14
15      KeyMed15   Medicament15
16      KeyMed16   Medicament16
17      KeyMed17   Medicament17
18      KeyMed18   Medicament18
19      KeyMed19   Medicament19

In [13]:
pandas_chambre_df.head(10)

     KeyChambre ChambreNumber
0   KeyChambre1          C001
1   KeyChambre2          C002
2   KeyChambre3          C003
3   KeyChambre4          C004
4   KeyChambre5          C005
5   KeyChambre6          C006
6   KeyChambre7          C007
7   KeyChambre8          C008
8   KeyChambre9          C009
9  KeyChambre10          C010

In [14]:
psdf_administration = ps.from_pandas(pandas_administration_df)
psdf_administration.to_csv('data_administration.csv')

/Users/giletcyp/anaconda3/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `to_spark`, the existing index is lost when converting to Spark DataFrame.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

In [15]:
psdf_medecins = ps.from_pandas(pandas_medecin_df)
psdf_medecins.to_csv('data_medecins.csv')

/Users/giletcyp/anaconda3/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `to_spark`, the existing index is lost when converting to Spark DataFrame.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

In [16]:
psdf_diagnostic = ps.from_pandas(pandas_diagnostic_df)
psdf_diagnostic.to_csv('data_diagnostics.csv')

/Users/giletcyp/anaconda3/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `to_spark`, the existing index is lost when converting to Spark DataFrame.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

In [17]:
psdf_treatment = ps.from_pandas(pandas_treatment_df)
psdf_treatment.to_csv('data_treatments.csv')

/Users/giletcyp/anaconda3/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `to_spark`, the existing index is lost when converting to Spark DataFrame.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

In [18]:
psdf_medicament = ps.from_pandas(pandas_medicament_df)
psdf_medicament.to_csv('data_medicaments.csv')

/Users/giletcyp/anaconda3/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `to_spark`, the existing index is lost when converting to Spark DataFrame.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

In [19]:
psdf_chambre = ps.from_pandas(pandas_chambre_df)
psdf_chambre.to_csv('data_chambres.csv')

/Users/giletcyp/anaconda3/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `to_spark`, the existing index is lost when converting to Spark DataFrame.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

In [20]:
psdf = ps.read_csv('data_administration.csv')
psdf.head(20)

/Users/giletcyp/anaconda3/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

         KeyConsult       KeyPatient       Name      FirstName  NumSecu    Date_In    Pathology     KeyChambre ChambreNumber   Date_Out
0   KeyConsult45056  KeyPatient10546  Name10546  FistName10546  NS45057 2023-11-25  Pathology22   KeyChambre81          C081 2023-11-26
1   KeyConsult45057  KeyPatient45482  Name45482  FistName45482  NS45058 2023-11-25  Pathology34  KeyChambre102          C102 2023-11-26
2   KeyConsult45058  KeyPatient37050  Name37050  FistName37050  NS45059 2023-11-25  Pathology84   KeyChambre22          C022 2023-12-05
3   KeyConsult45059  KeyPatient39793  Name39793  FistName39793  NS45060 2023-11-25  Pathology78    KeyChambre4          C004 2023-12-01
4   KeyConsult45060  KeyPatient17652  Name17652  FistName17652  NS45061 2023-11-25  Pathology15   KeyChambre29          C029 2023-11-26
5   KeyConsult45061  KeyPatient40034  Name40034  FistName40034  NS45062 2023-11-25   Pathology7   KeyChambre60          C060 2023-11-26
6   KeyConsult45062  KeyPatient38237  Name38237  FistName38237  NS45063 2023-11-25   Pathology7    KeyChambre5          C005 2023-11-27
7   KeyConsult45063  KeyPatient17519  Name17519  FistName17519  NS45064 2023-11-25  Pathology67   KeyChambre84          C084 2023-12-03
8   KeyConsult45064  KeyPatient28813  Name28813  FistName28813  NS45065 2023-11-25  Pathology56   KeyChambre51          C051 2023-11-26
9   KeyConsult45065  KeyPatient20313  Name20313  FistName20313  NS45066 2023-11-25  Pathology54   KeyChambre37          C037 2023-11-26
10  KeyConsult45066   KeyPatient6695   Name6695   FistName6695  NS45067 2023-11-25  Pathology26   KeyChambre66          C066 2023-11-26
11  KeyConsult45067  KeyPatient37007  Name37007  FistName37007  NS45068 2023-11-25  Pathology18   KeyChambre99          C099 2023-11-26
12  KeyConsult45068  KeyPatient20930  Name20930  FistName20930  NS45069 2023-11-25  Pathology78   KeyChambre83          C083 2023-11-30
13  KeyConsult45069  KeyPatient24582  Name24582  FistName24582  NS45070 2023-11-25  Pathology79   KeyChambre55          C055 2023-12-02
14  KeyConsult45070  KeyPatient26399  Name26399  FistName26399  NS45071 2023-11-25  Pathology82    KeyChambre9          C009 2023-12-04
15  KeyConsult45071   KeyPatient7663   Name7663   FistName7663  NS45072 2023-11-25  Pathology22   KeyChambre44          C044 2023-11-26
16  KeyConsult45072  KeyPatient29639  Name29639  FistName29639  NS45073 2023-11-25  Pathology66   KeyChambre64          C064 2023-11-27
17  KeyConsult45073   KeyPatient4542   Name4542   FistName4542  NS45074 2023-11-25  Pathology67  KeyChambre103          C103 2023-11-26
18  KeyConsult45074  KeyPatient26303  Name26303  FistName26303  NS45075 2023-11-25  Pathology20   KeyChambre95          C095 2023-11-27
19  KeyConsult45075  KeyPatient12358  Name12358  FistName12358  NS45076 2023-11-25  Pathology52           NULL          NULL 2023-11-25